#!/bin/sh
# Start udev early in boot
case "$1" in
  start)
    [ -x /sbin/udevd ] || [ -x /lib/systemd/systemd-udevd ] || exit 0
    if [ -x /sbin/udevd ]; then
      /sbin/udevd --daemon
    elif [ -x /lib/systemd/systemd-udevd ]; then
      /lib/systemd/systemd-udevd --daemon
    fi
    /sbin/udevadm trigger --action=add >/dev/null 2>&1 || true
    /sbin/udevadm settle >/dev/null 2>&1 || true
    ;;
  stop)
    killall udevd >/dev/null 2>&1 || true
    ;;
esac
exit 0
