#!/bin/sh
### BEGIN INIT INFO
# Provides:          smartcard-init
# Required-Start:
# Required-Stop:
# Default-Start:     S
# Default-Stop:
# Short-Description: Starts IFD-NFC on boot.
### END INIT INFO

start() {
	printf "Starting IFD-NFC: "
	if [ -x /usr/bin/ifdnfc-activate ]; then
		/usr/bin/ifdnfc-activate yes
		echo "OK"
	else
		echo "ifdnfc-activate not found"
		return 1
	fi
}

stop() {
	printf "Stopping IFD-NFC: "
	if [ -x /usr/bin/ifdnfc-activate ]; then
		/usr/bin/ifdnfc-activate no
		echo "OK"
	else
		echo "ifdnfc-activate not found"
		return 1
	fi
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		sleep 1
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 5
		;;
esac

exit $?
