#!/bin/sh
### BEGIN INIT INFO
# Provides:          pcscd
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: PC/SC Smart Card Daemon
### END INIT INFO

start() {
	printf "Starting pcscd: "
	pcscd &
	echo "OK"
}

stop() {
	printf "Stopping pcscd: "
	killall pcscd
	echo "OK"
}

restart() {
	stop
	sleep 1
	start
}

reload() {
	printf "Reloading pcscd: "
	pcscd --hotplug
	echo "OK"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	reload)
		reload
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 5
		;;
esac

exit $?
