#!/bin/sh

case "$1" in
  start)
    [ -x /sbin/udevd ] && /sbin/udevd --daemon
    [ -x /sbin/udevadm ] && /sbin/udevadm trigger --action=add
    [ -x /sbin/udevadm ] && /sbin/udevadm settle
    ;;
  stop)
    killall udevd 2>/dev/null || true
    ;;
  restart)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
